//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottery.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryUser
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> LotteryId { get; set; }
        public bool IsWinner { get; set; }
        public string Prize { get; set; }
    
        public virtual Lottery Lottery { get; set; }
        public virtual User User { get; set; }
    }
}
